service: cors-proxy

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 60
  stage: dev
  region: eu-west-1
  environment:
    foo: 123

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
